import { Solas } from '../../solas.js'

export const AUTOGEN_MSG = `// auto-generated by ${Solas.Config.NAME}`

const INDENT = '\t'
const IDENTIFIER = /^[$A-Z_a-z][$\w]*$/

/**
 * Check whether a string contains control characters that should never appear in source
 */
function hasControlChar(value: string) {
	for (let index = 0; index < value.length; index += 1) {
		const code = value.charCodeAt(index)

		if ((code >= 0 && code <= 31) || code === 127) {
			return true
		}
	}

	return false
}

/**
 * Validate an identifier before writing it into generated source unquoted
 */
export function toIdentifier(value: string, label: string) {
	if (!IDENTIFIER.test(value)) {
		throw new Error(`Invalid ${label}: ${value}`)
	}

	return value
}

/**
 * Validate and quote a relative specifier before embedding it in generated imports
 */
export function toRelativeModuleSpecifier(value: string, label: string) {
	if (value.length === 0) {
		throw new Error(`Invalid ${label}: module specifier cannot be empty`)
	}

	if (value.includes('\\')) {
		throw new Error(`Invalid ${label}: module specifier must use forward slashes`)
	}

	if (hasControlChar(value)) {
		throw new Error(`Invalid ${label}: module specifier contains control characters`)
	}

	if (!value.startsWith('./') && !value.startsWith('../')) {
		throw new Error(`Invalid ${label}: module specifier must be relative`)
	}

	return toStringLiteral(value)
}

/**
 * Validate a nullable identifier list whilst preserving explicit null holes
 */
export function toIdentifierList(values: readonly (string | null)[], label: string) {
	return values
		.map((value, index) =>
			value === null ? 'null' : toIdentifier(value, `${label}[${index}] identifier`),
		)
		.join(', ')
}

/**
 * Escape text into a safe string literal for generated source
 */
export function toStringLiteral(value: string, quoteStyle: "'" | '"' = "'") {
	return `${quoteStyle}${value
		.replace(/\\/g, '\\\\')
		.replace(new RegExp(quoteStyle, 'g'), `\\${quoteStyle}`)
		.replace(/\n/g, '\\n')
		.replace(/\r/g, '\\r')
		.replace(/\t/g, '\\t')}${quoteStyle}`
}

/**
 * Convert a string into a valid unquoted property key if possible, otherwise quote it
 * as a string literal for generated source
 */
function toPropertyKey(value: string) {
	return IDENTIFIER.test(value) ? value : toStringLiteral(value)
}

/**
 * Check whether a value is a simple literal that can be safely inlined in generated
 * source without risking syntax errors or readability issues, or whether it should
 * be printed on multiple lines for clarity
 */
function isInlineValue(value: unknown) {
	return (
		value === null ||
		typeof value === 'boolean' ||
		typeof value === 'number' ||
		typeof value === 'string'
	)
}

/**
 * Emit readable ts source for generated config and manifest data
 */
export function toSourceLiteral(value: unknown, level = 0): string {
	if (value === null) return 'null'

	if (typeof value === 'string') return toStringLiteral(value)
	if (typeof value === 'boolean' || typeof value === 'number') {
		return String(value)
	}
	if (typeof value === 'function') return value.toString()

	if (Array.isArray(value)) {
		if (value.length === 0) return '[]'

		const items = value.map(item => toSourceLiteral(item, level + 1))
		const inline = value.every(isInlineValue) && items.join(', ').length <= 60

		if (inline) return `[${items.join(', ')}]`

		return [
			'[',
			items.map(item => indent(item, level + 1)).join(',\n'),
			`${INDENT.repeat(level)}]`,
		].join('\n')
	}

	if (typeof value === 'object') {
		const entries = Object.entries(value)

		if (entries.length === 0) return '{}'

		return [
			'{',
			entries
				.map(([key, entryValue]) => {
					const prefix = `${INDENT.repeat(level + 1)}${toPropertyKey(key)}: `

					if (typeof entryValue === 'function') {
						const source = entryValue.toString()

						if (source.startsWith(`${key}(`) || source.startsWith(`async ${key}(`)) {
							return indent(source, level + 1)
						}

						return `${prefix}${source.replace(/\n/g, `\n${INDENT.repeat(level + 1)}`)}`
					}

					return `${prefix}${toSourceLiteral(entryValue, level + 1).replace(/\n/g, `\n${INDENT.repeat(level + 1)}`)}`
				})
				.join(',\n'),
			`${INDENT.repeat(level)}}`,
		].join('\n')
	}

	throw new Error(`Unsupported generated value type: ${typeof value}`)
}

/**
 * Indent each line of a block of source code by the specified level for embedding in
 * generated output
 */
function indent(value: string, level = 1) {
	const prefix = INDENT.repeat(level)

	return value
		.split('\n')
		.map(line => (line.length > 0 ? `${prefix}${line}` : line))
		.join('\n')
}
