import { Solas } from '../../solas'

export const AUTOGEN_MSG = `// auto-generated by ${Solas.Config.NAME}`

const IDENTIFIER = /^[$A-Z_a-z][$\w]*$/

/**
 * Check whether a string contains control characters that should never appear in source
 */
function hasControlChar(value: string) {
	for (let index = 0; index < value.length; index += 1) {
		const code = value.charCodeAt(index)

		if ((code >= 0 && code <= 31) || code === 127) {
			return true
		}
	}

	return false
}

/**
 * Validate a generated identifier before writing it into source unquoted
 */
export function toIdentifier(value: string, label: string) {
	if (!IDENTIFIER.test(value)) {
		throw new Error(`Invalid ${label}: ${value}`)
	}

	return value
}

/**
 * Validate a generated relative module specifier before embedding it in import code
 */
export function toRelativeModuleSpecifier(value: string, label: string) {
	if (value.length === 0) {
		throw new Error(`Invalid ${label}: module specifier cannot be empty`)
	}

	if (value.includes('\\')) {
		throw new Error(`Invalid ${label}: module specifier must use forward slashes`)
	}

	if (hasControlChar(value)) {
		throw new Error(`Invalid ${label}: module specifier contains control characters`)
	}

	if (!value.startsWith('./') && !value.startsWith('../')) {
		throw new Error(`Invalid ${label}: module specifier must be relative`)
	}

	return JSON.stringify(value)
}

/**
 * validate a list of generated identifiers whilst preserving explicit null holes
 */
export function toIdentifierList(ids: readonly (string | null)[], label: string) {
	return ids
		.map((id, index) =>
			id === null ? 'null' : toIdentifier(id, `${label}[${index}] identifier`),
		)
		.join(', ')
}
